dist: bionic
sudo: false
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-8
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-7
      - lcov

before_install:
  - pip install --user cpp-coveralls

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cd tests
  - mkdir cmake
  - cd cmake/
  - cmake --version
  - cmake ../
  - make
  - ctest --verbose

after_success:
  - lcov --capture --directory . --output-file coverage.info -b "$PWD/../../sources/" --no-external
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info

